#!/bin/bash
# ------------------------------------------------------------------------------
# <auto-generated>
#
#     This code was generated by a tool.
#
#     Changes to this file may cause incorrect behavior and will be lost if
#     the code is regenerated.
#
# </auto-generated>
# ------------------------------------------------------------------------------

set -e

# ------------------------------------------------------------------------------
# EXECUTION
# ------------------------------------------------------------------------------

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

if ! command -v dotnet &> /dev/null
then
    echo "Could not find 'dotnet' SDK. Please install it from https://dot.net"
    exit 1
fi

NUKE_BUILD_VERSION="9.0.4"
DOTNET_VERSION=$(dotnet --version)
if [ "$DOTNET_VERSION" != "8.0.302" ]
then
    echo "Warning: Different .NET SDK version found ($DOTNET_VERSION). Expected 8.0.302."
fi

BUILD_PROJECT_FILE="$SCRIPT_DIR/build/_build.csproj"
if [ ! -f "$BUILD_PROJECT_FILE" ]
then
    echo "Error: Build project could not be found at '$BUILD_PROJECT_FILE'."
    exit 1
fi

BUILD_ASSEMBLY="$SCRIPT_DIR/build/bin/Debug/net8.0/_build.dll"
if [ ! -f "$BUILD_ASSEMBLY" ] || [ "$BUILD_PROJECT_FILE" -nt "$BUILD_ASSEMBLY" ]
then
    echo "Building build project..."
    dotnet build "$BUILD_PROJECT_FILE" /nologo /v:m /flp:v=d
fi

export NUKE_BUILD_ASSEMBLY="$BUILD_ASSEMBLY"
export NUKE_BUILD_ROOT="$SCRIPT_DIR"
export NUKE_BUILD_SCRIPT="${BASH_SOURCE[0]}"

echo "Executing build..."
dotnet exec "$BUILD_ASSEMBLY" "$@"
