// ReSharper disable UnusedMember.Global
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GistGet.Resources;

#nullable enable

using System.Resources;

/// <summary>
/// A strongly-typed resource class for looking up localized strings.
/// </summary>
internal static class Messages
{
    private static ResourceManager? _resourceManager;

    /// <summary>
    /// Returns the cached ResourceManager instance used by this class.
    /// </summary>
    private static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager("GistGet.Resources.Messages", typeof(Messages).Assembly);

    /// <summary>
    /// Looks up a localized string similar to: Fetching package information from Gist...
    /// </summary>
    internal static string FetchingFromGist =>
        ResourceManager.GetString("FetchingFromGist", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: Saving package information to Gist...
    /// </summary>
    internal static string SavingToGist =>
        ResourceManager.GetString("SavingToGist", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: Saving pin information to Gist...
    /// </summary>
    internal static string SavingPinToGist =>
        ResourceManager.GetString("SavingPinToGist", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: Fetching installed packages...
    /// </summary>
    internal static string FetchingInstalledPackages =>
        ResourceManager.GetString("FetchingInstalledPackages", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: Loading package information from file...
    /// </summary>
    internal static string LoadingFromFile =>
        ResourceManager.GetString("LoadingFromFile", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: Fetching package information from URL...
    /// </summary>
    internal static string FetchingFromUrl =>
        ResourceManager.GetString("FetchingFromUrl", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: {0} has been installed and saved to Gist
    /// </summary>
    internal static string InstallSuccess =>
        ResourceManager.GetString("InstallSuccess", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: {0} has been uninstalled and saved to Gist
    /// </summary>
    internal static string UninstallSuccess =>
        ResourceManager.GetString("UninstallSuccess", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: {0} has been upgraded
    /// </summary>
    internal static string UpgradeSuccess =>
        ResourceManager.GetString("UpgradeSuccess", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: {0} has been upgraded and saved to Gist
    /// </summary>
    internal static string UpgradeAndSaveSuccess =>
        ResourceManager.GetString("UpgradeAndSaveSuccess", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: {0} has been pinned and saved to Gist
    /// </summary>
    internal static string PinAddSuccess =>
        ResourceManager.GetString("PinAddSuccess", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: {0} has been unpinned and saved to Gist
    /// </summary>
    internal static string PinRemoveSuccess =>
        ResourceManager.GetString("PinRemoveSuccess", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: Synchronization completed
    /// </summary>
    internal static string SyncCompleted =>
        ResourceManager.GetString("SyncCompleted", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: {0} packages exported to {1}
    /// </summary>
    internal static string ExportSuccess =>
        ResourceManager.GetString("ExportSuccess", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: {0} packages imported to Gist
    /// </summary>
    internal static string ImportSuccess =>
        ResourceManager.GetString("ImportSuccess", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: [sync] Starting synchronization...
    /// </summary>
    internal static string SyncStarting =>
        ResourceManager.GetString("SyncStarting", null) ?? string.Empty;

    /// <summary>
    /// Looks up a localized string similar to: Installed: {0}, Uninstalled: {1}, Failed: {2}
    /// </summary>
    internal static string SyncSummary =>
        ResourceManager.GetString("SyncSummary", null) ?? string.Empty;
}
